# Generated by Django 3.0.7 on 2021-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='C:\\Users\\sujal\\Desktop\\Django-stream\\web_stream\\media')),
                ('title', models.TextField(default='Course Video', max_length=100, verbose_name='video title')),
                ('poster', models.ImageField(upload_to='C:\\Users\\sujal\\Desktop\\Django-stream\\web_stream\\media')),
                ('slug', models.SlugField(default=models.TextField(default='Course Video', max_length=100, verbose_name='video title'), unique=True)),
            ],
        ),
    ]
