# Generated by Django 3.0.7 on 2021-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
