# Generated by Django 3.0.7 on 2021-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream', '0003_auto_20210425_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.ImageField(upload_to='posters'),
        ),
    ]
