# Generated by Django 3.0.7 on 2021-04-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream', '0004_auto_20210425_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
