# Generated by Django 3.0.7 on 2021-04-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream', '0005_video_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
