# Generated by Django 3.0.7 on 2021-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream', '0006_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='level',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='videoLength',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
    ]
