# Generated by Django 3.0.7 on 2021-04-26 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_stream', '0007_auto_20210425_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(default='Course Video', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoLength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VideoResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, max_length=500, null=True)),
                ('responded', models.DateTimeField(auto_now_add=True, null=True)),
                ('forVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stream.Video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
