# Generated by Django 3.0.7 on 2021-04-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream', '0008_auto_20210426_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresponse',
            name='forVideo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video_stream.Video'),
        ),
    ]
